config/routes.rb
Whoran::Application.routes.draw do

  devise_for :users
  resources :runs 
  resources :memberships
  resources :groups
  get "welcome/index"
  
  root :to => "welcome#index"
end

app/models/group.rb
class Group < ActiveRecord::Base

	has_many :memberships
	belongs_to :user
	def users
		users = []
		memberships.each do | membership |
			users << User.find_by_id(membership.user_id)
		end
		return users
	end
	
	def runs
		runs = []
		users.each do |user|
			user.runs.each do |run|
				runs << run
			end
		end
		return runs
	end
end

app/models/membership.rb
class Membership < ActiveRecord::Base

	belongs_to :user
	belongs_to :group

end

app/models/run.rb
class Run < ActiveRecord::Base

	belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	
	
  # Setup accessible (or protected) attributes for your model
	has_many :runs
	has_many :memberships
	has_many :groups
	
	def groups
		groups = []
		memberships.each do | membership |
			groups << Group.find_by_id(membership.group_id)
		end
		return groups
	end
	attr_accessible :email, :password, :password_confirmation, :remember_me, :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.xml
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    @group = Group.find(params[:id])
    @group_runs = @group.runs.sort_by {|run| run.date}

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.xml
  def create
  	@group = Group.new(params[:group])
    if not current_user.nil?
    	@group.user_id = current_user.id
		  respond_to do |format|
		    if @group.save
		    	Membership.create(:user_id => current_user.id, :group_id => @group.id)
		      format.html { redirect_to(@group, :notice => 'Group formed!') }
		      format.xml  { render :xml => @group, :status => :created, :location => @run }
		    else
		      format.html { render :action => "new" }
		      format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
		    end
	    end
    else
    	redirect_to root_path
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to(@group, :notice => 'Group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id])
    @group.memberships.each {|membership| membership.destroy}
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  # GET /memberships
  # GET /memberships.xml
  def index
    @groups = current_user.groups

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @memberships }
    end
  end

  # GET /memberships/1
  # GET /memberships/1.xml
  def show
    @membership = Membership.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @membership }
    end
  end

  # GET /memberships/new
  # GET /memberships/new.xml
  def new
    @membership = Membership.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @membership }
    end
  end

  # GET /memberships/1/edit
  def edit
    @membership = Membership.find(params[:id])
  end

  # POST /memberships
  # POST /memberships.xml
  def create
    @membership = Membership.new(params[:membership]) 
		@group = Group.find_by_id(@membership.group_id)
		
    respond_to do |format|
	    if not Membership.find_by_group_id_and_user_id(@membership.group_id, @membership.user_id).nil?
    		format.html { redirect_to(@group, :notice => 'You are already a member of that group!') }
    	elsif @membership.save
        format.html { redirect_to(@group, :notice => 'Successfully joined group.') }
        format.xml  { render :xml => @membership, :status => :created, :location => @membership }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @membership.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /memberships/1
  # PUT /memberships/1.xml
  def update
    @membership = Membership.find(params[:id])
		@group = Group.find_by_id(@membership.group_id)

    respond_to do |format|
      if @membership.update_attributes(params[:membership])
        format.html { redirect_to(@group, :notice => 'Membership was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @membership.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.xml
  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to(memberships_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  # GET /runs
  # GET /runs.xml
  def index
  	if current_user.nil?
  		@runs = Runs.all
  	else
	    @runs = current_user.runs
		end
		
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @runs }
    end
  end

  # GET /runs/1
  # GET /runs/1.xml
  def show
    @run = Run.find(params[:id])
    @user = User.find_by_id(@run.user_id)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @run }
    end
  end

  # GET /runs/new
  # GET /runs/new.xml
  def new
    @run = Run.new
    @run.time = Time.utc(0)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @run }
    end
  end

  # GET /runs/1/edit
  def edit
    @run = Run.find(params[:id])
  end

  # POST /runs
  # POST /runs.xml
  def create
    @run = Run.new(params[:run])
    if not current_user.nil?
    	@run.user_id = current_user.id
		  respond_to do |format|
		    if @run.save
		      format.html { redirect_to(runs_url, :notice => 'Run was successfully created.') }
		      format.xml  { render :xml => runs_url, :status => :created, :location => @run }
		    else
		      format.html { render :action => "new" }
		      format.xml  { render :xml => @run.errors, :status => :unprocessable_entity }
		    end
	    end
    else
    	redirect_to root_path
    end
  end

  # PUT /runs/1
  # PUT /runs/1.xml
  def update
    @run = Run.find(params[:id])

    respond_to do |format|
      if @run.update_attributes(params[:run])
        format.html { redirect_to(runs_url, :notice => 'Run was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @run.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.xml
  def destroy
    @run = Run.find(params[:id])
    @run.destroy

    respond_to do |format|
      format.html { redirect_to(runs_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Created By</th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= User.find_by_id(group.user_id).email %></td>
    <td><%= group.title %></td>
    <td><%= group.description %></td>
    <td><%= button_to 'Join this Group!', memberships_path({:membership => { :user_id => current_user.id, :group_id => group.id } })%></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<h2>  <%= @group.title %> </h2>
<p>
  <b>Founder:</b>
  <%= @group.user.email %>
</p>

<p>
  <%= @group.description %>
</p>

<!-- replace this with a calendar at some point -->
<table>
	<tr>
		<th> Date </th>
		<th> User </th>		
		<th> Distance </th>
		<th> Time </th>
	</tr>
<% @group_runs.each do |run| %>
	<tr>
    <td><%= run.date.month %>/<%= run.date.day%>/<%= run.date.year %></td>
		<td> <%= run.user.username %> </td>
    <td><%= run.distance %></td>
    <td><%= run.time.hour %>:<%= run.time.min %></td>
	</tr>
<% end %>

</table>

<% if @group.users.include?(current_user) %>
	<%= button_to 'Leate this Group', membership_path(@group.memberships.find_all_by_user_id(current_user.id)), :confirm => "Are you sure you want to leave this group?", :method => :delete%>
<% end %>
<% if current_user.id == @group.user_id %>
	<%= link_to 'Edit', edit_group_path(@group) %> <br />
	<%= button_to 'Disband this group.', @group, :confirm => "Are you sure you want to disband this group?", :method => :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whoran</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<%= render 'welcome/dashboard' %>

<%= yield %>

</body>
</html>

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.text_field :group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<h1> Your groups </h1>

<table>
  <tr>
    <th>Created By</th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= User.find_by_id(group.user_id).email %></td>
    <td><%= group.title %></td>
    <td><%= group.description %></td>
    <td><%= link_to 'Show', group %></td>
    <td><%= button_to 'Leate this Group', membership_path(group.memberships.find_all_by_user_id(current_user.id)), :confirm => "Are you sure you want to leave this group?", :method => :delete%></td>
  </tr>
<% end %>
</table>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @membership.user_id %>
</p>

<p>
  <b>Group:</b>
  <%= @membership.group_id %>
</p>


<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>

app/views/runs/_form.html.erb
<%= form_for(@run) do |f| %>
  <% if @run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@run.errors.count, "error") %> prohibited this run from being saved:</h2>

      <ul>
      <% @run.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :distance %><br />
    <%= f.text_field :distance %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <em> Time in hours and minutes </em> <br />
    <%= f.time_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/runs/edit.html.erb
<h1>Editing run</h1>

<%= render 'form' %>

<%= link_to 'Show', @run %> |
<%= link_to 'Back', runs_path %>

app/views/runs/index.html.erb
<h1>Listing runs</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Distance</th>
    <th>Time</th>
    <th></th>
    <th></th>
  </tr>

<% @runs.each do |run| %>
  <tr>
    <td><%= run.date.month %>/<%= run.date.day%>/<%= run.date.year %></td>
    <td><%= run.distance %></td>
    <td><%= run.time.hour %>:<%= run.time.min %></td>
    <td><%= link_to 'Edit', edit_run_path(run) %></td>
    <td><%= link_to 'Destroy', run, :confirm => 'Are you sure you want to remove this run?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Run', new_run_path %>

app/views/runs/new.html.erb
<h1>New run</h1>

<%= render 'form' %>

<%= link_to 'Back', runs_path %>

app/views/runs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Runner:</b>
  <%= @user.username %>
</p>
<p>
  <b>Date:</b>
  <%= @run.date %>
</p>

<p>
  <b>Distance:</b>
  <%= @run.distance %>
</p>

<p>
  <b>Time:</b>
  <%= @run.time %>
</p>


<%= link_to 'Edit', edit_run_path(@run) %> |
<%= link_to 'Back', runs_path %>

app/views/welcome/_dashboard.html.erb
<% if current_user.nil? %>
	<%= link_to "Sign in", new_user_session_path %> or <%= link_to "Sign up", new_user_registration_path %>
<% else %>
	Welcome, <%= current_user.username %>. <%= link_to "Log out", destroy_user_session_path %> <br />
	<%= link_to "Your Runs", runs_path %> |
	<%= link_to "Record a Run", new_run_path %> |
	<%= link_to "Your Groups", memberships_path %> |
	<%= link_to "Find New Groups", groups_path %> |
	<%= link_to "Form New Group", new_group_path %>
<% end %>

<h1> WhoRan? </h1>

app/views/welcome/_splash.html.erb
<h2> Welcome to WhoRan? </h2>

<p> This website is intended for you and your friends to keep track of your runs. Log in, create groups, and then start running! </p>

app/views/welcome/index.html.erb
<% if current_user.nil? %>
	<%= render 'welcome/splash' %>
<% end %>